name: Context Demo

on: workflow_dispatch

jobs:
  print-some-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: print some stuff
        run: |
          echo "Hello world, from our workflow"
          echo "Action name is: ${{ toJson(github) }}"
  
